# Generated by Django 6.0.3 on 2026-07-15 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_0002_user_country_0005_user_kyc_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Business Description"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kyc/logos/",
                verbose_name="Business Logo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_registration_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="CAC/Business Registration Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Business Started"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sole_proprietorship", "Sole Proprietorship"),
                    ("llc", "Limited Liability Company"),
                    ("partnership", "Partnership"),
                    ("corporation", "Corporation"),
                    ("nonprofit", "Non-Profit Organization"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
                verbose_name="Business Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bvn",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Bank Verification Number (BVN)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "International Passport"),
                    ("drivers_license", "Driver's License"),
                    ("voters_card", "Voter's Card"),
                    ("national_id", "National ID Card"),
                ],
                max_length=30,
                null=True,
                verbose_name="Government ID Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_stage",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("business_info", "Business Information"),
                    ("identity", "Identity Verification"),
                    ("contact", "Contact Verification"),
                    ("address", "Address Verification"),
                    ("banking", "Banking Details"),
                    ("guarantor", "Guarantor Information"),
                    ("compliance", "Product Compliance"),
                    ("documents", "Document Upload"),
                    ("internal_check", "Internal Checks (Admin)"),
                    ("quality_assurance", "Quality Assurance (Admin)"),
                    ("verified_seller", "Verified Seller"),
                    ("approved", "Fully Approved"),
                    ("rejected", "Rejected"),
                ],
                default="registration",
                max_length=30,
                verbose_name="KYC Stage",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="liveness_selfie",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kyc/selfies/",
                verbose_name="Liveness/Selfie Verification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nin",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="National Identification Number (NIN)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email OTP Verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_phone_verified",
            field=models.BooleanField(default=False, verbose_name="Phone OTP Verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kyc/passports/",
                verbose_name="Passport Photograph",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tin",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Tax Identification Number (TIN)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="utility_bill",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="kyc/utilities/",
                verbose_name="Utility Bill",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("occupation", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYCInternalCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nin_verified",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="NIN Verification",
                    ),
                ),
                (
                    "bvn_verified",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="BVN Verification",
                    ),
                ),
                (
                    "bank_matched",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Bank Account Match",
                    ),
                ),
                (
                    "cac_verified",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="CAC Verification",
                    ),
                ),
                (
                    "nafdac_verified",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="NAFDAC Verification",
                    ),
                ),
                (
                    "otp_verified",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="OTP Verification",
                    ),
                ),
                (
                    "duplicate_checked",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Duplicate Check",
                    ),
                ),
                (
                    "fraud_checked",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Fraud Check",
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("na", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Overall Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Internal Notes"
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_checks_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nafdac_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="NAFDAC Registration Number",
                    ),
                ),
                (
                    "nafdac_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="kyc/compliance/nafdac/",
                        verbose_name="NAFDAC Certificate",
                    ),
                ),
                (
                    "son_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="SON Registration Number",
                    ),
                ),
                (
                    "son_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="kyc/compliance/son/",
                        verbose_name="SON Certificate",
                    ),
                ),
                (
                    "has_labels",
                    models.BooleanField(
                        default=False, verbose_name="Product Labels Compliant"
                    ),
                ),
                (
                    "ingredients_list",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ingredients List"
                    ),
                ),
                (
                    "batch_tracking",
                    models.BooleanField(
                        default=False, verbose_name="Batch Number Tracking"
                    ),
                ),
                (
                    "expiry_date_policy",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Expiry Date Management Policy",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Compliance Verified by Admin"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityAssurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_photos_ok",
                    models.BooleanField(
                        default=False, verbose_name="Shop/Warehouse Photos OK"
                    ),
                ),
                (
                    "packaging_photos_ok",
                    models.BooleanField(
                        default=False, verbose_name="Packaging Photos OK"
                    ),
                ),
                (
                    "inventory_photos_ok",
                    models.BooleanField(
                        default=False, verbose_name="Inventory Photos OK"
                    ),
                ),
                (
                    "supplier_invoices_ok",
                    models.BooleanField(
                        default=False, verbose_name="Supplier Invoices OK"
                    ),
                ),
                (
                    "authenticity_proof_ok",
                    models.BooleanField(
                        default=False, verbose_name="Authenticity Proof OK"
                    ),
                ),
                (
                    "qa_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="QA Inspector Notes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("passed", "Passed"),
                            ("failed", "Failed - Needs Corrections"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("qa_date", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="kyc/shop_photos/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("accepted_orders", models.PositiveIntegerField(default=0)),
                ("shipped_on_time", models.PositiveIntegerField(default=0)),
                ("total_shipped", models.PositiveIntegerField(default=0)),
                ("returned_orders", models.PositiveIntegerField(default=0)),
                ("delivered_orders", models.PositiveIntegerField(default=0)),
                ("complaints", models.PositiveIntegerField(default=0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("sum_ratings", models.PositiveIntegerField(default=0)),
                ("refunded_orders", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendor Performance Metrics",
            },
        ),
        migrations.CreateModel(
            name="VerifiedSellerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                (
                    "inspection_done",
                    models.BooleanField(
                        default=False, verbose_name="Physical Inspection Completed"
                    ),
                ),
                (
                    "video_interview_done",
                    models.BooleanField(
                        default=False, verbose_name="Video Interview Completed"
                    ),
                ),
                (
                    "supplier_references_ok",
                    models.BooleanField(
                        default=False, verbose_name="Supplier References Verified"
                    ),
                ),
                (
                    "quality_audit_ok",
                    models.BooleanField(
                        default=False, verbose_name="Quality Audit Passed"
                    ),
                ),
                (
                    "badge_displayed",
                    models.BooleanField(
                        default=False, verbose_name="Badge Displayed on Products"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_seller_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Verified Seller Statuses",
            },
        ),
    ]
