# Generated by Django 5.2.7 on 2026-02-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Order Placed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("arrived", "Arrived in Destination Country"),
                            ("delivered", "Delivered"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paystack_ref", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
